/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-06-04 05:05:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class status2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/first/WEB-INF/lib/spring-webmvc-5.0.5.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1522752190000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.0.5.RELEASE.jar", Long.valueOf(1525933211405L));
    _jspx_dependants.put("jar:file:/C:/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/first/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/first/WEB-INF/lib/spring-webmvc-5.0.5.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1522752190000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1520823355453L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".carinfo{\r\n");
      out.write("font-weight:500;\r\n");
      out.write("font-size:15px;\r\n");
      out.write("color: #aebbd0;\r\n");
      out.write("/* letter-spacing:2px; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".chartcon{\r\n");
      out.write("float: left; width: 40%;height:3cm;\r\n");
      out.write("margin-left:10px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".chartinfo{\r\n");
      out.write("padding-top:43px;\r\n");
      out.write("padding-right:25px;\r\n");
      out.write("width: 40%;\r\n");
      out.write("float:right;\r\n");
      out.write("text-align:right;\r\n");
      out.write("font-size:17px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".distance{\r\n");
      out.write("\r\n");
      out.write("width:44.4%;\r\n");
      out.write("height:3cm;\r\n");
      out.write("margin-left:0px;\r\n");
      out.write("margin-right:0.3cm;\r\n");
      out.write("float:left;\r\n");
      out.write("background-color:#384861;\r\n");
      out.write("height:3cm;\r\n");
      out.write("}\r\n");
      out.write(".infotitle{\r\n");
      out.write("color:#bec9da;\r\n");
      out.write("}\r\n");
      out.write(".infocon{\r\n");
      out.write("padding-right:0.5cm;\r\n");
      out.write("margin-top:0.8cm;\r\n");
      out.write("text-align:right;\r\n");
      out.write("font-size:70px;\r\n");
      out.write("color: #17b7c8;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write(".infounit{\r\n");
      out.write("color:#bec9da;\r\n");
      out.write("\r\n");
      out.write("margin-left:0.5cm;\r\n");
      out.write("font-size:25px;\r\n");
      out.write("}\r\n");
      out.write(".infocon2{\r\n");
      out.write("color: #3abdb4;\r\n");
      out.write("\r\n");
      out.write("padding-right:0.4cm;\r\n");
      out.write("margin-top:0.9cm;\r\n");
      out.write("text-align:right;\r\n");
      out.write("font-size:50px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".infounit2{\r\n");
      out.write("color:#bec9da;\r\n");
      out.write("\r\n");
      out.write("margin-bottom:0.5cm;\r\n");
      out.write("margin-left:0.3cm;\r\n");
      out.write("font-size:20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".first{\r\n");
      out.write("height:3cm;\r\n");
      out.write("}\r\n");
      out.write(".secgridone{\r\n");
      out.write("width:41%;\r\n");
      out.write("float:left;\r\n");
      out.write("height:70%;\r\n");
      out.write("}\r\n");
      out.write("#secgrid{\r\n");
      out.write("float:left;\r\n");
      out.write("width:56%;\r\n");
      out.write("margin-top:0px;\r\n");
      out.write("margin-left:0.3cm;\r\n");
      out.write("margin-right:0px;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".secinfo{\r\n");
      out.write("width:41.6%;\r\n");
      out.write("float:left;\r\n");
      out.write("}\r\n");
      out.write(".thirdinfo{\r\n");
      out.write("width:98.3%;\r\n");
      out.write("margin-top:0.3cm;\r\n");
      out.write("height:5.45cm;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script async defer\r\n");
      out.write("   src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyDKy-W18gyBXJQGDU2diCyAdo_0nzc2ze0&callback=initMap\"\r\n");
      out.write("   type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("   src=\"http://beneposto.pl/jqueryrotate/js/jQueryRotateCompressed.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 도넛 차트 넣어보기 -->\r\n");
      out.write("<script src=\"https://code.highcharts.com/highcharts.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/modules/variable-pie.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/highcharts.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function display1(data){\r\n");
      out.write("   var drivingchart=new \r\n");
      out.write("   Highcharts.Chart( {\r\n");
      out.write("       chart: {\r\n");
      out.write("          renderTo:'driving',\r\n");
      out.write("           backgroundColor: 'none',\r\n");
      out.write("           height: (9/16 * 100) + '%', \r\n");
      out.write("           spacingBottom:25,\r\n");
      out.write("           spacingLeft:35,\r\n");
      out.write("\r\n");
      out.write("       },\r\n");
      out.write("\r\n");
      out.write("       title: {\r\n");
      out.write("           text: '월별 주행거리',           \r\n");
      out.write("             margin:0,\r\n");
      out.write("           style: {\r\n");
      out.write("               \r\n");
      out.write("                 color:' #bec9da',\r\n");
      out.write("                 fontSize: \"13px\"\r\n");
      out.write("              \r\n");
      out.write("              }    \r\n");
      out.write("        \r\n");
      out.write("       },\r\n");
      out.write("       yAxis:{\r\n");
      out.write("          gridLineColor: 'transparent',\r\n");
      out.write("          title: {\r\n");
      out.write("                text: \"\"\r\n");
      out.write("            },\r\n");
      out.write("            labels: {\r\n");
      out.write("                format: '{value} km',\r\n");
      out.write("                style: {\r\n");
      out.write("                    color: '#bec9da'\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("\r\n");
      out.write("       },\r\n");
      out.write("       xAxis: {\r\n");
      out.write("            lineColor: 'transparent',\r\n");
      out.write("            minorTickLength: 0,\r\n");
      out.write("             tickLength: 0,\r\n");
      out.write("           categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',\r\n");
      out.write("               'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],\r\n");
      out.write("               \r\n");
      out.write("               labels: {\r\n");
      out.write("                   style: {\r\n");
      out.write("                       color: '#bec9da'\r\n");
      out.write("                   }\r\n");
      out.write("               },\r\n");
      out.write("       },\r\n");
      out.write("\r\n");
      out.write("       plotOptions: {\r\n");
      out.write("           series: {\r\n");
      out.write("               borderColor: 'transparent',\r\n");
      out.write("               color:'rgb(62, 197, 204)'\r\n");
      out.write("           }\r\n");
      out.write("       },\r\n");
      out.write("\r\n");
      out.write("       series: [{\r\n");
      out.write("\r\n");
      out.write("           data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],\r\n");
      out.write("           type: 'column'\r\n");
      out.write("       }]\r\n");
      out.write("\r\n");
      out.write("   });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" $(document).ready(function(){\r\n");
      out.write("      \r\n");
      out.write("      $.ajax({\r\n");
      out.write("            url:'chart1impl.do',\r\n");
      out.write("            success:function(datas){\r\n");
      out.write("               display1(datas);\r\n");
      out.write("               \r\n");
      out.write("              // alert('ok'+datas);\r\n");
      out.write("          },\r\n");
      out.write("            error:function(){\r\n");
      out.write("               alert('fail');         \r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("\r\n");
      out.write("   }); \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("function display(datas){\r\n");
      out.write("   var gas= parseFloat(datas[0]['gas']);\r\n");
      out.write("   var tire= parseFloat(datas[0]['tire']);\r\n");
      out.write("   var engtmp=parseFloat(datas[0]['engtmp']);\r\n");
      out.write("   var char1=new Highcharts.Chart({\r\n");
      out.write("       chart: {\r\n");
      out.write("          renderTo: 'container',\r\n");
      out.write("           type: 'variablepie',\r\n");
      out.write("           backgroundColor: 'none',\r\n");
      out.write("         margin: [0,0,0,0],\r\n");
      out.write("      spacing: [0,0,0,0]\r\n");
      out.write("           \r\n");
      out.write("       },\r\n");
      out.write("       \r\n");
      out.write("       credits: {\r\n");
      out.write("            enabled: false\r\n");
      out.write("        },\r\n");
      out.write("   \r\n");
      out.write("        tooltip: {\r\n");
      out.write("            enabled: false\r\n");
      out.write("        },\r\n");
      out.write("        plotOptions: {\r\n");
      out.write("       \r\n");
      out.write("            series: {\r\n");
      out.write(" /*                     size:'100%', */\r\n");
      out.write("            \r\n");
      out.write("               borderColor: 'rgb(255, 255, 255,0)',\r\n");
      out.write("                dataLabels: {\r\n");
      out.write("                  enabled: false\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("       title: {\r\n");
      out.write("           text:gas+\" L\",\r\n");
      out.write("/*          align: 'center',\r\n");
      out.write(" */\r\n");
      out.write("          verticalAlign: 'middle',\r\n");
      out.write("          floating: true,\r\n");
      out.write("          x: 0,\r\n");
      out.write("          y: 6,\r\n");
      out.write("          margin:0,\r\n");
      out.write("           style: {\r\n");
      out.write("     \r\n");
      out.write("              color:' #bec9da',\r\n");
      out.write("        \r\n");
      out.write("           }           \r\n");
      out.write("       },\r\n");
      out.write("       series: [{\r\n");
      out.write("          size: 120,\r\n");
      out.write("         innerSize: 78,\r\n");
      out.write("         pointPadding: 0,\r\n");
      out.write("         groupPadding: 0,\r\n");
      out.write("     /*   minPointSize: 10,\r\n");
      out.write("           zMin: 0, */\r\n");
      out.write("           name: 'Gas',\r\n");
      out.write("           data: [{\r\n");
      out.write("              color:'rgb(62, 197, 204,0.7)',\r\n");
      out.write("               name: '주유',\r\n");
      out.write("               y: gas,\r\n");
      out.write("               z: 5\r\n");
      out.write("           }, {\r\n");
      out.write("              \r\n");
      out.write("/*               color:'rgb(239, 241, 246,0.8)',\r\n");
      out.write(" */               name: '',\r\n");
      out.write("               y: 110-gas,\r\n");
      out.write("               z: 1\r\n");
      out.write("           }]\r\n");
      out.write("       }]\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   var char2=new Highcharts.Chart( {\r\n");
      out.write("       chart: {\r\n");
      out.write("          renderTo: 'container2',\r\n");
      out.write("           type: 'variablepie',\r\n");
      out.write("           backgroundColor: 'none',\r\n");
      out.write("\r\n");
      out.write("            margin: [0,0,0,0],\r\n");
      out.write("         spacing: [0,0,0,0]\r\n");
      out.write("           \r\n");
      out.write("       },\r\n");
      out.write("       \r\n");
      out.write("       credits: {\r\n");
      out.write("            enabled: false\r\n");
      out.write("        },\r\n");
      out.write("   \r\n");
      out.write("        tooltip: {\r\n");
      out.write("           enabled: false \r\n");
      out.write("        },\r\n");
      out.write("        plotOptions: {\r\n");
      out.write("            series: {\r\n");
      out.write("               borderColor: 'rgb(255, 255, 255,0)',\r\n");
      out.write("                dataLabels: {\r\n");
      out.write("                   enabled: false\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("       title: {\r\n");
      out.write("           text: tire+\" psi\",\r\n");
      out.write("           align: 'center',\r\n");
      out.write("           verticalAlign: 'middle',\r\n");
      out.write("           floating: true,\r\n");
      out.write("           x: 0,\r\n");
      out.write("           y: 6,\r\n");
      out.write("           margin:0,\r\n");
      out.write("           style: {\r\n");
      out.write("     \r\n");
      out.write("              color:'#bec9da'\r\n");
      out.write("           }           \r\n");
      out.write("       },\r\n");
      out.write("       series: [{\r\n");
      out.write("          size: 120,\r\n");
      out.write("         innerSize: 78,\r\n");
      out.write("         pointPadding: 0,\r\n");
      out.write("         groupPadding: 0,\r\n");
      out.write("           name: 'tire',\r\n");
      out.write("           data: [{\r\n");
      out.write("              color:'rgb(58, 189, 180,0.7)',\r\n");
      out.write("               name: 'Spain',\r\n");
      out.write("               y: tire,\r\n");
      out.write("               z: 80\r\n");
      out.write("           }, {\r\n");
      out.write("              \r\n");
      out.write("/*               color:'rgb(239, 241, 246,0.8)',\r\n");
      out.write(" */               name: 'France',\r\n");
      out.write("               y: 45-tire,\r\n");
      out.write("               z: 1\r\n");
      out.write("           }]\r\n");
      out.write("       }]\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   var char3=new Highcharts.Chart( {\r\n");
      out.write("       chart: {\r\n");
      out.write("          renderTo: 'container3',\r\n");
      out.write("           type: 'variablepie',\r\n");
      out.write("           backgroundColor: 'none',\r\n");
      out.write("\r\n");
      out.write("            margin: [0,0,0,0],\r\n");
      out.write("         spacing: [0,0,0,0]\r\n");
      out.write("       },\r\n");
      out.write("       \r\n");
      out.write("       credits: {\r\n");
      out.write("            enabled: false\r\n");
      out.write("        },\r\n");
      out.write("   \r\n");
      out.write("        tooltip: {\r\n");
      out.write("            enabled: false\r\n");
      out.write("        },\r\n");
      out.write("        plotOptions: {\r\n");
      out.write("            series: {\r\n");
      out.write("               borderColor: 'rgb(255, 255, 255,0)',\r\n");
      out.write("                dataLabels: {\r\n");
      out.write("                     enabled: false\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("       title: {\r\n");
      out.write("          \r\n");
      out.write("           text: engtmp+\"°C\",\r\n");
      out.write("       /*     align: 'center', */\r\n");
      out.write("           verticalAlign: 'middle',\r\n");
      out.write("           floating: true,\r\n");
      out.write("           x: 0,\r\n");
      out.write("           y: 6,\r\n");
      out.write("           margin:0,\r\n");
      out.write("           style: {\r\n");
      out.write("              color:'#bec9da',              \r\n");
      out.write("/*               fontSize: '20px',\r\n");
      out.write(" */\r\n");
      out.write("           }           \r\n");
      out.write("       },\r\n");
      out.write("       series: [{\r\n");
      out.write("          size: 120,\r\n");
      out.write("         innerSize: 78,\r\n");
      out.write("         pointPadding: 0,\r\n");
      out.write("         groupPadding: 0,\r\n");
      out.write("           name: 'engtmp',\r\n");
      out.write("           data: [{\r\n");
      out.write("              color:'rgb(255, 102, 153,0.7)',\r\n");
      out.write("               name: 'Spain',\r\n");
      out.write("               y: engtmp,\r\n");
      out.write("               z: 80\r\n");
      out.write("           }, {\r\n");
      out.write("              \r\n");
      out.write("/*               color:'rgb(239, 241, 246,0.8)',\r\n");
      out.write(" */               name: 'France',\r\n");
      out.write("               y: 130-engtmp,\r\n");
      out.write("               z: 1\r\n");
      out.write("           }]\r\n");
      out.write("       }]\r\n");
      out.write("   });\r\n");
      out.write("}\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("   \r\n");
      out.write("   $.ajax({\r\n");
      out.write("         url:'chart1impl.do',\r\n");
      out.write("         success:function(datas){\r\n");
      out.write("            display(datas);            \r\n");
      out.write("           // alert('ok'+datas);\r\n");
      out.write("       },\r\n");
      out.write("         error:function(){\r\n");
      out.write("            alert('fail');         \r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("}); \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("//지도\r\n");
      out.write("function initialize(input) {\r\n");
      out.write("\r\n");
      out.write("   var mapOptions = {\r\n");
      out.write("      zoom : 15,\r\n");
      out.write("      center : input[0],\r\n");
      out.write("      mapTypeId : google.maps.MapTypeId.ROADMAP\r\n");
      out.write("   }\r\n");
      out.write("   var map = new google.maps.Map(document.getElementById('map_canvas'),\r\n");
      out.write("         mapOptions);\r\n");
      out.write("         var myLatlng = new google.maps.LatLng(input[0]); // y, x좌표값\r\n");
      out.write("         var marker = new google.maps.Marker({\r\n");
      out.write("            position : myLatlng,\r\n");
      out.write("            icon: 'view/images/carpin.png',\r\n");
      out.write("            map : map\r\n");
      out.write("\r\n");
      out.write("         });\r\n");
      out.write("         var address= JSON.stringify(input[0]['address']);\r\n");
      out.write("   /*       var iwContent ='<div style=\"font-weight:bold;font-size: 5px;letter-spacing:-1px;\">위치: '+address+'</div>'\r\n");
      out.write("         var infowindow = new google.maps.InfoWindow({\r\n");
      out.write("            content : iwContent,\r\n");
      out.write("            maxWidth : 300\r\n");
      out.write("         });\r\n");
      out.write("         google.maps.event.addListener(marker, 'mouseover', function() {\r\n");
      out.write("            infowindow.open(map, marker);\r\n");
      out.write("         });\r\n");
      out.write("         google.maps.event.addListener(marker, 'mouseout', function() {\r\n");
      out.write("            infowindow.close();\r\n");
      out.write("         }); */\r\n");
      out.write("\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("   // Server에 데이터를 요청한다.\r\n");
      out.write("   // AJAX로\r\n");
      out.write("   $.ajax({\r\n");
      out.write("      url : 'mystate.do',\r\n");
      out.write("      dataType : 'json',\r\n");
      out.write("      success : function(data) {\r\n");
      out.write("         //alert(data);\r\n");
      out.write("         initialize(data);\r\n");
      out.write("      },\r\n");
      out.write("      error : function(e) {\r\n");
      out.write("         alert('fail');\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<header></header>\r\n");
      out.write("<section style=\"padding:20px;\">\r\n");
      out.write("                            \r\n");
      out.write("   <div class=\"mdl-grid mdl-grid--no-spacing\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"mdl-grid mdl-cell mdl-cell--9-col-desktop mdl-cell--12-col-tablet mdl-cell--4-col-phone mdl-cell--top\">\r\n");
      out.write("<div style=\" float: left; width: 27%;margin:0px;\" class=\"mdl-grid mdl-cell mdl-cell--9-col-desktop mdl-cell--12-col-tablet mdl-cell--4-col-phone mdl-cell--top\">\r\n");
      out.write("                <div style=\"width:100%;\" class=\"mdl-cell mdl-cell--4-col-desktop mdl-cell--4-col-tablet mdl-cell--2-col-phone\">\r\n");
      out.write("               <div style=\"width:100%;height:7cm;padding:0;\"class=\"mdl-card mdl-shadow--2dp robot\">\r\n");
      out.write("                <div style=\"padding:0px;height:90%;\" class=\"mdl-card__title mdl-card--expand\">\r\n");
      out.write("<img src=\"img/car2.gif\" style=\"width:100%;height:100%;float:left;\" id=\"image\">\r\n");
      out.write("         </div>\r\n");
      out.write("              \r\n");
      out.write("                <div style=\"padding:0px;height:10%;\" class=\"mdl-card__supporting-text\">\r\n");
      out.write("                <div style=\"width:0.1cm;height:100%; background-color:#3ec5cc;float:left; margin-right:0.2cm;\"></div>\r\n");
      out.write("                   <div style=\"padding-top:0.1cm;\"> ");
      out.write("<span class=\"carinfo\">  Last updated  </span> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div> \r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                 \r\n");
      out.write("                <div style=\"width:100%; margin-top:0.5cm;\" class=\"mdl-cell mdl-cell--4-col-desktop mdl-cell--4-col-tablet mdl-cell--2-col-phone\">\r\n");
      out.write("                    <div style=\"background-color:rgb(62, 197, 204,0);\" class=\"mdl-card mdl-shadow--2dp weather\">\r\n");
      out.write("                        <div style=\"background-color:#384861; height:0.8cm;\" class=\"mdl-card__title\">\r\n");
      out.write("                            <h2 class=\"mdl-card__title-text\"></h2>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mdl-layout-spacer\"></div>\r\n");
      out.write("                            <div style=\"color:#bec9da;\" class=\"mdl-card__subtitle-text\">\r\n");
      out.write("                                <i style=\"color: #3ec5cc;\" class=\"material-icons\">room</i>\r\n");
      out.write("                               ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mdl-card__supporting-text mdl-card--expand\" id=\"map_canvas\" style=\"float : left\"></div>\r\n");
      out.write("                            \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("</div>\r\n");
      out.write("<div  style=\"margin:1px; float: left; width: 72%;\" class=\"mdl-grid mdl-cell mdl-cell--9-col-desktop mdl-cell--12-col-tablet mdl-cell--4-col-phone mdl-cell--top\">\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                <div  class=\" first mdl-cell mdl-cell--3-col-desktop mdl-cell--3-col-tablet mdl-cell--2-col-phone\">\r\n");
      out.write("                    <div  class=\"mdl-card mdl-shadow--2dp trending\">\r\n");
      out.write("                       <!--  <div style=\"background-color: #384861;\"class=\"mdl-card__title\">\r\n");
      out.write("                            <h2 class=\"mdl-card__title-text\">Trending</h2>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("                        <div class=\"mdl-card__supporting-text\" style=\"width:100%;height:3cm;'\">\r\n");
      out.write("                         <div  class=\"chartcon\" id=\"container\"></div>\r\n");
      out.write("                         <div class=\"chartinfo\" style=\"color:rgb(62, 197, 204);\">GAS</div>\r\n");
      out.write("                         \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"first mdl-cell mdl-cell--3-col-desktop mdl-cell--3-col-tablet mdl-cell--2-col-phone\">\r\n");
      out.write("                    <div class=\"mdl-card mdl-shadow--2dp trending\">\r\n");
      out.write("                       <!--  <div style=\"background-color: #384861;\"class=\"mdl-card__title\">\r\n");
      out.write("                            <h2 class=\"mdl-card__title-text\">Trending</h2>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("                        <div class=\"mdl-card__supporting-text\" style=\"width:100%;height:3cm;\">\r\n");
      out.write("                         <div class=\"chartcon\" id=\"container2\"></div>\r\n");
      out.write("                                                  <div class=\"chartinfo\" style=\"color:rgb(58, 189, 180);\">Tire Pressure</div>\r\n");
      out.write("                         \r\n");
      out.write("                         \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"first mdl-cell mdl-cell--3-col-desktop mdl-cell--3-col-tablet mdl-cell--2-col-phone\">\r\n");
      out.write("                    <div class=\"mdl-card mdl-shadow--2dp trending\">\r\n");
      out.write("                \r\n");
      out.write("                        <div class=\"mdl-card__supporting-text\" style=\"width:100%;height:3cm;\">\r\n");
      out.write("                         <div class=\"chartcon\" id=\"container3\" ></div>\r\n");
      out.write("                                                  <div class=\"chartinfo\" style=\"color:rgb(255, 102, 153);\">Engine Temperature</div>\r\n");
      out.write("                         \r\n");
      out.write("                         \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("      <div class=\"mdl-cell mdl-cell--7-col-desktop mdl-cell--7-col-tablet mdl-cell--4-col-phone\" style=\"margin-top:0.4cm; margin-left:0px; width:100%;\" id=\"second\">\r\n");
      out.write("\r\n");
      out.write("<!--                 <div style=\"width:100%;\"class=\"mdl-cell mdl-cell--7-col-desktop mdl-cell--7-col-tablet mdl-cell--4-col-phone\">\r\n");
      out.write(" -->                    <div style=\"width:100%; float:left; margin-right:0.5cm;  margin-bottom:0.3cm;\" class=\"mdl-grid mdl-cell mdl-cell--3-col-desktop mdl-cell--12-col-tablet mdl-cell--4-col-phone mdl-cell--top\">\r\n");
      out.write("                     <div  class=\"distance mdl-card__supporting-text\" >\r\n");
      out.write("                     <div class=\"infotitle\">주행가능거리</div>    <div class=\"infocon\"> 910<span class=\"infounit\">km</span> </div>\r\n");
      out.write("                     \r\n");
      out.write("                    </div>\r\n");
      out.write("                     <div  class=\"distance mdl-card__supporting-text\">\r\n");
      out.write("                     <div class=\"infotitle\">총 주행거리</div>    <div class=\"infocon\"> 3136<span class=\"infounit\">km</span></div>\r\n");
      out.write("                     \r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                 <div style=\"width:100%; margin-top:0px; \" class=\"mdl-grid mdl-cell mdl-cell--3-col-desktop mdl-cell--12-col-tablet mdl-cell--4-col-phone mdl-cell--top\">\r\n");
      out.write("                   <div class=\"secgridone mdl-card mdl-shadow--2dp line-chart\">\r\n");
      out.write("     \r\n");
      out.write("                        <div class=\"mdl-card__supporting-text\">\r\n");
      out.write("                            <div class=\"line-chart__container\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div >\r\n");
      out.write("                    \r\n");
      out.write("                        <div id=\"secgrid\" class=\"mdl-grid mdl-cell mdl-cell--3-col-desktop mdl-cell--12-col-tablet mdl-cell--4-col-phone mdl-cell--top\">\r\n");
      out.write("                       <div  class=\"secinfo distance mdl-card__supporting-text\" >\r\n");
      out.write("                     <div class=\"infotitle\">평균연비</div>    <div class=\"infocon2\"> 15.4<span class=\"infounit2\">km/L</span></div>\r\n");
      out.write("                     \r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div style=\"margin-right:0px;\" class=\"secinfo distance mdl-card__supporting-text\" >\r\n");
      out.write("                     <div class=\"infotitle\">차내 온도</div>    <div class=\"infocon2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartemp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <span class=\"infounit2\">°C</span> </div>\r\n");
      out.write("                     \r\n");
      out.write("                    </div>\r\n");
      out.write("                      <div class=\"thirdinfo mdl-card mdl-shadow--2dp line-chart\">\r\n");
      out.write("     \r\n");
      out.write("                        <div style=\"padding:0px;\" class=\"mdl-card__supporting-text\">\r\n");
      out.write("                            \r\n");
      out.write("<div id=\"driving\" style=\"min-width: 310px; height: 5.5cm; margin: 0 auto\"></div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("      \r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<footer></footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
